additional profile related fixes and cleanups

diff --git a/genkernel b/genkernel
--- a/genkernel
+++ b/genkernel
@@ -34,25 +34,46 @@ do
 	parse_cmdline $Option
 done
 
+genkernel_determine_arch
+
 # Failed to parse the cmdline properly, die so we can investigate...
 logicTrue ${__INTERNAL__CONFIG_PARSING_FAILED} && die 'Fatal error processing arguments; exiting...'
 
 
-#profile_list
-#profile_delete "profile__home_eje001_profile"
-profile_list
-profile_copy "profile__home_eje001_profile" "running"
-profile_copy "cmdline" "running"
+# Start Importing profiles into the running profile space
+
+# Copy in the system wide defaults
+profile_copy "system"
+
+# import the arch specific profile. Arch specific system overrides.
+profile_copy "arch"
+# Read arch-specific config
+#ARCH_CONFIG="${CONFIG_DIR}/config.sh"
+#[ -f "${ARCH_CONFIG}" ] || die "${ARCH} not yet supported by genkernel. Please add the arch-specific config file, ${ARCH_CONFIG}"
+#source ${ARCH_CONFIG} || die "Could not read ${ARCH_CONFIG}"
+
+# Copy the user profile created with the setup_userspace function. Last profile to import
+# as this one overrides the rest of them.
+profile_copy "user"
+
+# End Importing profiles into the running profile space
 
 
 set_color 
-logicTrue $(config_get_key help) && show_help && echo && exit 0 # --help
+logicTrue $(config_get_key help user) && show_help && echo && exit 0 # --help
+
 
 # Set DEBUGFILE if log-override is defined
 [ -n "$(config_get_key log-override)" ] && DEBUGFILE="$(config_get_key log-override)"
 
 # Set TEMP if tempdir is defined
 [ -n "$(config_get_key tempdir)" ] && TEMP="$(config_get_key tempdir)"
+
+# Generate TEMP dir
+if [ ! -d "${TEMP}" ]
+then
+	mkdir -p "${TEMP}" || die "Failed to create temporary directory!"
+fi
 
 [ -n "$(config_get_key profile-dump)" ] && config_profile_dump
 
@@ -67,20 +88,10 @@ fi
 clear_log
 
 genkernel_print_header
-genkernel_determine_arch
-
-CACHE_DIR="$(arch_replace ${CACHE_DIR})"
-CONFIG_DIR="$(arch_replace ${CONFIG_DIR})"
-[ -e "${CACHE_DIR}" ] || mkdir -p "${CACHE_DIR}"
-[ -e "${CONFIG_DIR}" ] || mkdir -p "${CONFIG_DIR}"
-
-# Read arch-specific config
-ARCH_CONFIG="${CONFIG_DIR}/config.sh"
-[ -f "${ARCH_CONFIG}" ] || die "${ARCH} not yet supported by genkernel. Please add the arch-specific config file, ${ARCH_CONFIG}"
-source ${ARCH_CONFIG} || die "Could not read ${ARCH_CONFIG}"
-
 genkernel_lookup_packages
 genkernel_lookup_kernel
+
+
 # Process depends
 print_info 1 '>> Processing dependency tree...'
 require "${__INTERNAL__CONFIG_PARSING_DEPTREE}"
@@ -95,15 +106,10 @@ genkernel_lookup_packages
 genkernel_lookup_kernel silent
 require "${__INTERNAL__CONFIG_PARSING_DEPTREE}"
 
-# Generate TEMP dir
-if [ ! -d "${TEMP}" ]
-then
-	mkdir -p "${TEMP}" || die "Failed to create temporary directory!"
-fi
-
 #Create the cache dir if it doesnt exist
 setup_cache_dir
 
+# Genkernel module...
 genkernel::()
 {
 	print_info 1 '>> Dependencies processed successfully!'
