Working modules load code

diff --git a/genkernel b/genkernel
--- a/genkernel
+++ b/genkernel
@@ -15,6 +15,7 @@ source ${CORE_DIR}/gen_coreFunctions.sh || die "Failed to source gen_coreFunctio
 source ${CORE_DIR}/gen_dependencyEngine.sh || die "Failed to source gen_dependencyEngine.sh"
 source ${CORE_DIR}/gen_processPackages.sh || die "Failed to source gen_processPackages.sha"
 source ${CORE_DIR}/gen_processKernelTree.sh || die "Failed to source gen_processKernelTree.sh"
+source ${CORE_DIR}/gen_processKernelModules.sh || die "Failed to source gen_processKernelModules.sh"
 source ${CORE_DIR}/gen_cmdline.sh || die "Failed to source gen_cmdline.sh"
 source ${CORE_DIR}/gen_help_setup.sh || die "Failed to source gen_help_setup.sh"
 source ${CORE_DIR}/gen_initialize.sh || die "Failed to source gen_initialize.sh"
@@ -37,6 +38,10 @@ done
 genkernel_determine_arch
 import_arch_profile 
 
+import_kernel_module_load_list
+
+echo "Module category list: $(kernel_modules_category_list)"
+echo "$(kernel_modules_category_lookup scsi)"
 # Failed to parse the cmdline properly, die so we can investigate...
 logicTrue ${__INTERNAL__CONFIG_PARSING_FAILED} && die 'Fatal error processing arguments; exiting...'
 
@@ -53,10 +58,6 @@ profile_copy "arch"
 profile_copy "user"
 
 # End Importing profiles into the running profile space
-echo "${__INTERNAL__OPTIONS__KEY[@]}"
-echo "${__INTERNAL__OPTIONS__VALUE[@]}"
-echo "${__INTERNAL__OPTIONS__PROFILE[@]}"
-echo "MODULES: $(config_get_key 'evms' 'modules')"
 
 set_color 
 logicTrue $(config_get_key help user) && show_help && echo && exit 0 # --help
