fix log-override

diff --git a/genkernel b/genkernel
--- a/genkernel
+++ b/genkernel
@@ -67,6 +67,19 @@ profile_copy "system"
 # as this one overrides the rest of them. This contains the cmdline and imported profiles
 profile_copy "user"
 
+
+# Set DEBUGFILE if log-override is defined
+[ -n "$(profile_get_key log-override)" ] && DEBUGFILE="$(profile_get_key log-override)"
+
+# Set TEMP if tempdir is defined
+[ -n "$(profile_get_key tempdir)" ] && TEMP="$(profile_get_key tempdir)"
+
+# Generate TEMP dir
+if [ ! -d "${TEMP}" ]
+then
+	mkdir -p "${TEMP}" || die "Failed to create temporary directory!"
+fi
+
 set_color 
 clear_log
 genkernel_print_header
@@ -87,12 +100,6 @@ then
 fi
 
 logicTrue $(profile_get_key help user) && show_help && echo && exit 0 # --help
-
-# Set DEBUGFILE if log-override is defined
-[ -n "$(profile_get_key log-override)" ] && DEBUGFILE="$(profile_get_key log-override)"
-
-# Set TEMP if tempdir is defined
-[ -n "$(profile_get_key tempdir)" ] && TEMP="$(profile_get_key tempdir)"
 
 # Generate TEMP dir
 if [ ! -d "${TEMP}" ]
